feat(PPP-3): fix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,6 +34,13 @@ jobs:
       - name: Ensure Gradle build generates JAR
         run: ./gradlew build
 
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f build/libs/paw-paradise-back-0.0.1-SNAPSHOT.jar ]; then
+            echo "JAR file not found!";
+            exit 1;
+          fi
+
       - name: Build Docker image
         run: docker build -t trebor006/paw-paradise-back:latest .
 
